---
- name: create nextcloud www volume
  file:
    path: "{{www_volume}}"
    state: directory
    owner: "{{www_data_uid}}"
    group: root
    mode: 0755

- name: create database volume
  file:
    path: "{{database_volume}}"
    state: directory
    owner: "{{database_uid}}"
    group: root
    mode: 0700
