---
- name: Create systemd unit file for nextcloud
  template:
    src: nextcloud.systemd.j2
    dest: "/etc/systemd/system/{{service_name}}.service"
    owner: root
    group: root
    mode: 0644
  register: nextcloud_service

- name: Create systemd unit file for nextcloud add-missing-indices
  template:
    src: nextcloud.add-missing-indices.systemd.j2
    dest: "/etc/systemd/system/{{indices_service_name}}.service"
    owner: root
    group: root
    mode: 0644
  register: nextcloud_indices_service

- name: Create systemd timer file for nextcloud add-missing-indices
  template:
    src: nextcloud.add-missing-indices.timer.j2
    dest: "/etc/systemd/system/{{indices_service_name}}.timer"
    owner: root
    group: root
    mode: 0644
  register: nextcloud_indices_timer

- name: Reload systemd
  command: systemctl daemon-reload
  when: >
    nextcloud_service.changed
    or nextcloud_indices_service.changed
    or nextcloud_indices_timer.changed

- name: Setup nextcloud fix-indices timer
  systemd:
    name: "{{indices_service_name}}.timer"
    state: started
    enabled: yes
