---
- name: Create systemd unit file for nextcloud
  template:
    src: nextcloud.systemd.j2
    dest: "/etc/systemd/system/{{ service_name }}.service"
    owner: root
    group: root
    mode: 0644
  register: nextcloud_service
  notify:
    - Restart nextcloud service
