---
- name: create nextcloud www volume
  file:
    path: "{{ nextcloud_www_volume }}"
    state: directory
    owner: "{{ nextcloud_www_data_uid }}"
    group: root
    mode: 0750

- name: create database volume
  file:
    path: "{{ nextcloud_database_volume }}"
    state: directory
    owner: "{{ nextcloud_database_uid }}"
    group: root
    mode: 0700
