---
- name: Use openssl to generate secret
  shell: "openssl rand -hex {{secret_size}}"
  changed_when: false
  register: generated_openssl_secret

- name: Set new secret fact
  set_fact:
    generated_secret: "{{generated_openssl_secret.stdout}}"
