---
- include_tasks: generate-one-secret.yml

- name: Setup postgres user password
  copy:
    dest: "{{ nextcloud_db_secret_file_path }}"
    content: "{{ generated_secret }}"
    owner: root
    group: root
    mode: 0640
