---
- include: generate-one-secret.yml

- debug:
    var: generated_secret

- name: Setup postgres user password
  copy:
    dest: "{{postgres_password_file_path}}"
    content: "{{generated_secret}}"
