---
- name: pull image
  docker_image:
    name: "{{image_name}}:{{image_version}}"
    source: pull
  register: dockerimage

- include: create_volumes.yml

- name: Create systemd unit file
  template: src=nextcloud.systemd.j2 dest=/etc/systemd/system/nextcloud.service owner=root group=root mode=0550
  register: nextcloud_service

- name: Reload systemd
  command: systemctl daemon-reload
  when: nextcloud_service.changed

- name: Restart service (on changes)
  service:
    name: nextcloud
    state: restarted
    enabled: yes
  when: nextcloud_service.changed or dockerimage.changed

- name: Start service (if not started)
  service:
    name: nextcloud
    state: started
