---
- include_tasks: setup-docker-environment.yml
- include_tasks: create-volumes.yml

- include_tasks: create-systemd-services.yml
- include_tasks: setup-background-job.yml

- name: Start systemd-managed docker containers
  meta: flush_handlers

- name: Enable/start nextcloud service (if not started)
  service:
    name: "{{ nextcloud_service_name }}"
    enabled: true
    state: started
  when: not (
    molecule_docker_environment is defined
    and molecule_docker_environment | bool
    )

- name: Enable/start nextcloud-background-jobs service (if not started)
  systemd:
    name: "{{ nextcloud_background_service_name }}.service"
    enabled: true
  when: not (
    molecule_docker_environment is defined
    and molecule_docker_environment | bool
    )

- name: Enable/start nextcloud-background-jobs timer (if not started)
  systemd:
    name: "{{ nextcloud_background_service_name }}.timer"
    enabled: true
    state: started
  when: not (
    molecule_docker_environment is defined
    and molecule_docker_environment | bool
    )
