---
- name: pull image
  docker_image:
    name: "{{image_name}}:{{image_version}}"

- include: create_volumes.yml

- name: Create systemd unit file
  template: src=nextcloud.systemd.j2 dest=/etc/systemd/system/nextcloud.service owner=root group=root mode=0550
  register: nextcloud_service

- name: Reload systemd
  command: systemctl daemon-reload
  when: nextcloud_service.changed

- name: Restart service
  service: name=nextcloud state=restarted enabled=yes
  when: nextcloud_service.changed
