---
- name: pull image
  docker_image:
    name: "{{image_name}}:{{image_version}}"
    source: pull
  register: dockerimage

- include: create_volumes.yml

- include: create-systemd-services.yml

- name: Restart service (on changes)
  service:
    name: "{{service_name}}"
    state: restarted
    enabled: yes
  when: nextcloud_service.changed or dockerimage.changed

- name: Start service (if not started)
  service:
    name: "{{service_name}}"
    state: started
