---
- include: check-parameters.yml
- include: setup-docker-environment.yml
- include: create-volumes.yml

- include: create-systemd-services.yml

- name: Start systemd-managed docker containers
  meta: flush_handlers

- name: Enable/start nextcloud service (if not started)
  service:
    name: "{{ nextcloud_service_name }}"
    enabled: true
    state: started
  when: not (
    molecule_docker_environment is defined
    and molecule_docker_environment | bool
    )
