---
- include: check-parameters.yml
- include: setup-docker-environment.yml
- include: create-volumes.yml

- include: create-systemd-services.yml

- name: Start systemd-managed docker containers
  meta: flush_handlers
