---
- name: create background job service
  template:
    src: nextcloud-background-jobs.systemd.j2
    dest: "/etc/systemd/system/{{ nextcloud_background_service_name }}.service"
    owner: root
    group: root
    mode: 0644
  notify: Reload nextcloud-background-jobs service

- name: create background job timer
  template:
    src: nextcloud-background-jobs.timer.j2
    dest: "/etc/systemd/system/{{ nextcloud_background_service_name }}.timer"
    owner: root
    group: root
    mode: 0644
  notify: Reload nextcloud-background-jobs timer
