---
- name: create docker working directory
  file:
    path: "{{ nextcloud_docker_working_directory }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Check if postgres password file exists
  stat:
    path: "{{ nextcloud_db_secret_file_path }}"
  register: postgres_password_file_result

- include: generate-postgres-password.yml
  when: not (postgres_password_file_result.stat.exists | bool)

- name: template docker-image file
  template:
    src: Dockerfile.j2
    dest: "{{ nextcloud_dockerfile_path }}"
    owner: root
    group: root
    mode: 0644
  notify: Restart nextcloud service

- name: template docker-compose file
  template:
    src: docker-compose.yml.j2
    dest: "{{ nextcloud_docker_compose_path }}"
    owner: root
    group: root
    mode: 0644
  notify: Restart nextcloud service
