---
dependency:
  name: galaxy
  options:
    role-file: ./molecule/default/requirements.yml

driver:
  name: vagrant
  provider:
    name: libvirt

platforms:
  - name: ansible-nextcloud-xenial
    box: generic/ubuntu1604
  - name: ansible-nextcloud-bionic
    box: generic/ubuntu1804
  - name: ansible-nextcloud-focal
    box: generic/ubuntu2004
  - name: ansible-nextcloud-stretch
    box: generic/debian9
    groups:
      - debian
  - name: ansible-nextcloud-buster
    box: generic/debian10
    groups:
      - debian

provisioner:
  name: ansible
  playbooks:
    prepare: ../default/prepare.yml
    converge: ../default/converge.yml
    verify: ../default/verify.yml
  inventory:
    group_vars:
      debian:
        ansible_python_interpreter: /usr/bin/python3

verifier:
  name: ansible
