---
- name: Verify
  hosts: all
  become: true

  tasks:
    - name: Should template docker-compose file
      stat:
        path: /opt/nextcloud/docker/docker-compose.yml
      register: docker_file
      failed_when: not docker_file.stat.exists

    - name: Should nextcloud systemd unit file
      stat:
        path: /etc/systemd/system/nextcloud.service
      register: nextcloud_service_file
      failed_when: not nextcloud_service_file.stat.exists

    - name: Should nextcloud-background-jobs service systemd unit file
      stat:
        path: /etc/systemd/system/nextcloud-background-jobs.service
      register: nextcloud_background_service_file
      failed_when: not nextcloud_background_service_file.stat.exists

    - name: Should nextcloud-background-jobs timer systemd unit file
      stat:
        path: /etc/systemd/system/nextcloud-background-jobs.timer
      register: nextcloud_background_timer_file
      failed_when: not nextcloud_background_timer_file.stat.exists

    - name: Should create www volume
      stat:
        path: /srv/nextcloud/www
      register: www_volume_directory
      failed_when: not www_volume_directory.stat.exists

    - name: Should create database volume
      stat:
        path: /srv/nextcloud/database
      register: database_volume_directory
      failed_when: not database_volume_directory.stat.exists

    - name: Should open 10081/tcp port
      command: nc -z -w1 localhost 10081
      changed_when: false
      register: netcat_10081
      retries: 300
      delay: 1
      until: netcat_10081 is defined
        and netcat_10081.rc == 0
