---
- name: Prepare
  hosts: all
  become: true

  roles:
    - role: install-docker
      docker_storage_driver: overlay2
      docker_cleanup_enabled: false
      docker_install_pip_package: false
      when: not (
        molecule_docker_environment is defined
        and molecule_docker_environment | bool
        )

    - role: install-docker-compose
      docker_compose_version: 1.25.5
      docker_compose_install_from_pip: false
      docker_compose_bash_completion: false
      when: not (
        molecule_docker_environment is defined
        and molecule_docker_environment | bool
        )
