FROM nextcloud:{{ nextcloud_image_version }}

MAINTAINER borisskert <boris.skert@gmail.com>

{% if nextcloud_additional_apt_packages is defined and nextcloud_additional_apt_packages | length > 0 %}
RUN set -ex; \
    \
    apt-get update; \
    apt-get install -y --no-install-recommends \
{% for apt_package in nextcloud_additional_apt_packages %}
        {{ apt_package }} \
{% endfor %}
        ; \
    rm -rf /var/lib/apt/lists/*;
{% endif %}
