---
name: Run tests

'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  molecule_test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"

      - name: Run default tests
        uses: borisskert/molecule-action@v21.01.08
        with:
          arguments: test

      - name: Run 'all-parameters' tests
        uses: borisskert/molecule-action@v21.01.08
        with:
          arguments: test --scenario-name all-parameters
